### ISSUE TITLE
[COP] - Poltergeists are totally invisible no particles around them

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#995] opened 2022-04-07 00:21 UTC
**Describe the bug**
Poltergesit usually have some particles with electrical sparks textures present, but at the moment they appear without any particles around, they throw the boxes around to hurt you, and make the electrical sounds but are completely invisible

**To Reproduce**
go SouthWest of Zaton to the downed Helicopter, there is at least a Poltergeist there.

**Expected behavior**
they should have their particles showing up

**Screenshots**
none, but... that's the point isn't it?

**BugTrap error report**
maybe there is some textures not loading? so I provide the full console messages of opening the game and loading a game besides the poltergeist:

<details>
<summary>Click here to expand/collapse.</summary>
<p>
$ gdb --args xr_3da
GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xr_3da...
(No debugging symbols found in xr_3da)
(gdb) run
Starting program: /usr/games/xr_3da 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec50f640 (LWP 29879)]
[New Thread 0x7fffebbcd640 (LWP 29880)]
[New Thread 0x7fffeb3cc640 (LWP 29881)]
[New Thread 0x7fffeabcb640 (LWP 29882)]
[New Thread 0x7fffea3ca640 (LWP 29883)]
[New Thread 0x7fffe9bc9640 (LWP 29884)]
[New Thread 0x7fffe93c8640 (LWP 29885)]
[New Thread 0x7fffe8bc7640 (LWP 29886)]
[New Thread 0x7fffe83c6640 (LWP 29887)]
[New Thread 0x7fffe7bc5640 (LWP 29888)]
[New Thread 0x7fffe73c4640 (LWP 29889)]
[New Thread 0x7fffe6bc3640 (LWP 29890)]
[New Thread 0x7fffe5fc2640 (LWP 29891)]
[Thread 0x7fffe5fc2640 (LWP 29891) exited]
[New Thread 0x7fffe5fc2640 (LWP 29892)]
[Thread 0x7fffe5fc2640 (LWP 29892) exited]
! Couldn't create surface from image: Couldn't open logo.bmp
OpenXRay Release Master Gold build 8459, Apr  5 2022 (Linux 64-bit, shared)
Custom build from commit[afce361865adcd9fc877544cbff321c29ea7f7de] branch[dev]
 
command line 

* Detected CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx [AuthenticAMD], F15/M8/S1, 'rdtsc'
* CPU features: RDTSC, Invariant TSC, MMX, SSE, SSE2, SSE3, MONITOR/MWAIT, SSSE3, SSE4.1, SSE4.2, AVX, AVX2
* CPU cores/threads: 8/8
* CPU current freq: 2300 MHz

[New Thread 0x7fffe5fc2640 (LWP 29894)]
[New Thread 0x7fffe55c1640 (LWP 29895)]
[New Thread 0x7fffe4dc0640 (LWP 29896)]
[New Thread 0x7fffe45bf640 (LWP 29897)]
[New Thread 0x7fffe3dbe640 (LWP 29898)]
[New Thread 0x7fffe35bd640 (LWP 29899)]
[New Thread 0x7fffe2dbc640 (LWP 29900)]
Initializing File System...
$fs_root$ = /home/biel/.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/
using fs-ltx fsgame.ltx
FS: 39963 files cached 29 archives, 12Kb memory used.
Init FileSystem 0.295183 sec
-----loading \home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
-----loading \home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
! Failed to determine on which monitor the game is launched.
! SDL: Invalid window
Starting INPUT device...
Loading module: xrRender_GL
[New Thread 0x7fffe21ee640 (LWP 29901)]
[Thread 0x7fffe21ee640 (LWP 29901) exited]
[New Thread 0x7fffe21ee640 (LWP 29902)]
[Thread 0x7fffe21ee640 (LWP 29902) exited]
Available render modes[1]:
renderer_rgl
Executing config-script "user.ltx"...
[\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
Selected renderer: renderer_rgl
Loading module: xrGame
Initializing Engine...
[New Thread 0x7fffe21ee640 (LWP 29903)]
[Thread 0x7fffe21ee640 (LWP 29903) exited]
Executing config-script "\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
Executing config-script "user.ltx"...
Executing config-script "\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_extreme.ltx"...
[\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\rspec_extreme.ltx] successfully loaded.
Executing config-script "\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
[\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx] successfully loaded.
~ Invalid syntax in call to 'sv_adm_menu_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
~ Invalid syntax in call to 'sv_suspicious_actions_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
[\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
SOUND: OpenAL: system default sound device name is OpenAL Soft
[New Thread 0x7fffe21ee640 (LWP 29904)]
[Thread 0x7fffe21ee640 (LWP 29904) exited]
[New Thread 0x7fffe21ee640 (LWP 29905)]
[New Thread 0x7fffcf2ee640 (LWP 29907)]
[New Thread 0x7fffcf0ed640 (LWP 29908)]
[Thread 0x7fffcf0ed640 (LWP 29908) exited]
[Thread 0x7fffcf2ee640 (LWP 29907) exited]
SOUND: Selected device is OpenAL Soft
[Thread 0x7fffe21ee640 (LWP 29905) exited]
[New Thread 0x7fffe21ee640 (LWP 29909)]
[New Thread 0x7fffcf2ee640 (LWP 29910)]
[New Thread 0x7fffcf0ed640 (LWP 29911)]
* sound: EAX 2.0 extension: absent
* sound: EAX 2.0 deferred: absent
* sound : cache: 65537 kb, 4856 lines, 13820 bpl
Starting RENDER device...
[New Thread 0x7fffceeec640 (LWP 29912)]
[New Thread 0x7fffce6eb640 (LWP 29913)]
* GPU vendor: [AMD] device: [AMD Radeon(TM) Vega 10 Graphics (RAVEN, DRM 3.41.0, 5.13.0-39-generic, LLVM 12.0.1)]
* GPU OpenGL version: 4.6 (Core Profile) Mesa 21.2.6
* GPU OpenGL shading language version: 4.60
* GPU OpenGL VTF units: [32] CTI units: [192]
* DVB created: 4096K
* DIB created: 512K
! Renderer doesn't support blender 'effects\shadow_world'
* HWDST/PCF supported and used
Starting engine...
* [ Linux ]: free[631940 K], reserved[26488 K], committed[7260680 K]
* [ Render ]: textures[4153 K]
* [ x-ray  ]: process heap[193 K]
* [ x-ray  ]: economy: strings[7919 K], smem[0 K]
* phase time: 0 ms
* phase cmem: 211 K
Loading sounds...
Loading objects...
Loading models...
Loading textures...
* [prefetch] time:   2323 ms
* [prefetch] memory: 177 Kb
* phase time: 2327 ms
* phase cmem: 389 K
* phase time: 50 ms
* phase cmem: 392 K
* phase time: 0 ms
* phase cmem: 392 K
* Loading spawn registry...
* 6464 spawn points are successfully loaded
* Loading objects...
* 11575 objects are successfully loaded
* Game testlight is successfully loaded from file '\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\savedgames\testlight.scop' (1.026s)
* phase time: 1026 ms
* phase cmem: 621 K
* phase time: 23 ms
* phase cmem: 623 K
* phase time: 2 ms
* phase cmem: 623 K
* client : connection accepted - <All Ok>
* phase time: 3 ms
* phase cmem: 623 K
* phase time: 2 ms
* phase cmem: 623 K
* phase time: 458 ms
* phase cmem: 845 K
* phase time: 191 ms
* phase cmem: 845 K
* phase time: 622 ms
* phase cmem: 845 K
* phase time: 50 ms
* phase cmem: 845 K
* [DETAILS] VertexConsts(256), Batch(61)
* [DETAILS] 10126 v(20), 5368 p
* [DETAILS] Batch(61), VB(197K), IB(31K)
* phase time: 15 ms
* phase cmem: 845 K
* Loading HOM: \home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\levels\zaton\level.hom
* phase time: 4 ms
* phase cmem: 845 K
* phase time: 1 ms
* phase cmem: 845 K
* phase time: 1 ms
* phase cmem: 845 K
* phase time: 2 ms
* phase cmem: 845 K
* t-report - base: 1484, 63455 K
* t-report - lmap: 16, 1022 K
~ [ui\pda_tasks_16.xml] stretch attribute is unsupported for [background]
! Can't find texture 'ui_ingame2_pda_buttons_background_e'
! Can't find texture 'ui_pda2_fr_l'
! Can't find texture 'ui_pda2_fr_r'
! Can't find texture 'ui_pda2_fr_t'
! Can't find texture 'ui_pda2_fr_lt'
! Can't find texture 'ui_pda2_fr_rb'
! Can't find texture 'ui_pda2_fr_rt'
! Can't find texture 'ui_pda2_fr_lb'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_back'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_l'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_r'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_t'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_b'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_lt'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_rb'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_rt'
! Can't find texture 'ui_pda2_fr_delimiter_fraction_lb'
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [background]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line1]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line2]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line3]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line4]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line_left]
~ [ui\pda_fraction_war_16.xml] stretch attribute is unsupported for [static_line_right]
~ [ui\pda_logs_16.xml] stretch attribute is unsupported for [background]
* phase time: 1611 ms
* phase cmem: 845 K
! Unknown command:  dump_infos
* MEMORY USAGE: 852 K
* End of synchronization A[1] R[1]
* phase time: 3576 ms
* phase cmem: 852 K
* [ Linux ]: free[115948 K], reserved[12840 K], committed[7969576 K]
* [ Render ]: textures[67938 K]
* [ x-ray  ]: process heap[852 K]
* [ x-ray  ]: economy: strings[24665 K], smem[10238 K]
* [ Linux ]: free[126612 K], reserved[13048 K], committed[7958912 K]
* [ Render ]: textures[67938 K]
* [ x-ray  ]: process heap[882 K]
* [ x-ray  ]: economy: strings[24666 K], smem[10237 K]
- Disconnect
- Destroying level
* [ D3D ]: textures[47360 K]
Config-file [\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] saved successfully
Destroying Render...
</p>
</details>

**Desktop (please complete the following information):**
 - OS: [Ubuntu 21.10]
 - OpenXRay build version [5388bce0d738ed39c8070fdbabbcba0dcfdfede3] with ``` -DMASTER_GOLD=OFF ```

**Additional context**
none

**Comment by Xottab-DUTY** [comment] 2022-04-07 09:25
Duplicate of #935

**Closed as completed** 2022-04-07 09:25 UTC
Labels: Duplicate
