### ISSUE TITLE
Linux - segmentation fault at launch after mimalloc

### ISSUE THREAD

**Issue by BielBdeLuna** [Swartz27/xray-16#1197] opened 2022-12-27 02:17 UTC
**Describe the bug**
launching the engine gets a segfault

**To Reproduce**
just laucnh the engine... `$ xr_3da` 

**BugTrap error report**

<details><summary>CLICK ME</summary>
<p>

```

$ xr_3da 
! Couldn't create surface from image: Parameter 'src' is invalid
OpenXRay Release Master Gold build 8725, Dec 27 2022 (Linux 64-bit, shared)
Custom build from commit[16c8717ac8e17796b3ee55d58fc96e6e8b764763] branch[dev]
 
command line 

* CPU features: RDTSC, MMX, SSE, AVX
* CPU threads: 8

Initializing File System...
$fs_root$ = /home/biel/.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/
using fs-ltx fsgame.ltx
FS: 40598 files cached 29 archives, 14Kb memory used.
Init FileSystem 0.340334 sec
-----loading \home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
-----loading \home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\system.ltx
! Failed to determine on which monitor the game is launched.
! SDL: Invalid window
Starting INPUT device...
Loading module: xrRender_GL
Available render modes[1]:
renderer_rgl
Executing config-script "user.ltx"...
[\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\_appdata_\user.ltx] successfully loaded.
Selected renderer: renderer_rgl
Loading module: xrGame
Initializing Engine...
SOUND: OpenAL: system default sound device name is OpenAL Soft
Executing config-script "\home\biel\.local\share\GSC Game World\S.T.A.L.K.E.R. - Call of Pripyat\gamedata\configs\default_controls.ltx"...
mimalloc: warning: mi_free: pointer might not point to a valid heap region: 0x5568c9ebaa00
(this may still be a valid very large allocation (over 64MiB))
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/biel/code/xray/OpenXRay/src/xrCore/xrDebug.cpp
[error] Line          : 866
[error] Description   : segmentation fault
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/lib/x86_64-linux-gnu/xrCore.so(+0x4330b) [0x7f41bf84430b]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bcf0) [0x7f41bec3bcf0]
/lib/x86_64-linux-gnu/libmimalloc.so.2(__libc_free+0x209) [0x7f41bef862f9]
StringFromUTF8[abi:cxx11](char const*, std::locale const&)
KbdKeyToButtonName(int, std::__cxx11::basic_string<char, std::char_traits<char>, xalloc<char> >&)
CInput::GetKeyName(int, char*, int)
/lib/x86_64-linux-gnu/xrEngine.so(+0x9629e) [0x7f41bfa6429e]
CCC_Bind::Execute(char const*)
CConsole::ExecuteCommand(char const*, bool)
CCC_LoadCFG::Execute(char const*)
CConsole::ExecuteCommand(char const*, bool)
CCC_DefControls::Execute(char const*)
CConsole::ExecuteCommand(char const*, bool)
execUserScript()
Startup()
RunApplication()
xr_3da(+0x18a6) [0x5568c958b8a6]
xr_3da(+0x15df) [0x5568c958b5df]
mimalloc: warning: mi_free: pointer might not point to a valid heap region: 0x5568c9eb9a70
(this may still be a valid very large allocation (over 64MiB))
Violació de segment (s'ha bolcat la memòria)


```

</p>
</details>

**Desktop (please co```mplete the following information):**
 - OS: [Linux 22.10]
 - OpenXRay  [16c8717ac8e17796b3ee55d58fc96e6e8b764763]

**Comment by Xottab-DUTY** [comment] 2022-12-27 11:26
Duplicate of #1193

**Closed as completed by Xottab-DUTY** 2022-12-27 11:26 UTC
Labels: Duplicate
