### ISSUE TITLE
CoP crashes when travelling to Zaton after reaching Pripyat

### ISSUE THREAD

**Issue by Random-Heretic** [Swartz27/xray-16#1577] opened 2023-12-30 09:07 UTC
**Describe the bug**
Game crashes when travelling to Zaton from Pripyat or Yanov after completing the Missing recon unit mission

**Steps to reproduce the behavior:**
1. Complete 'Missing recon unit'
2. Talk to Garry and ask him to take you to Zaton OR travel to Yanov and then ask Pilot to take you to Zaton
3. Game crashes when loading Zaton

**Expected behavior**
I expected to load into Zaton like it should

**Screenshots, videos**
![image](https://github.com/OpenXRay/xray-16/assets/105509998/5c47a2c4-bf1a-4c9f-99b9-2e2fecec036b)

**BugTrap error report**
[OpenXRay_error_report_231229-202326.zip](https://github.com/OpenXRay/xray-16/files/13797588/OpenXRay_error_report_231229-202326.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenXRay build version: December 2020 Preview

**Additional context**
Already posted a question on the official Discord on 29/12/2023 at 20:27. Figured I'd also submit it here to keep things organised.
I am also using the Pripyat Reclamation Patch, however all forums mentioned that the two are compatible.

**Comment by Xottab-DUTY** [comment] 2024-05-26 16:28
I believe, this should have been fixed in April/May.
Please, check it out and reopen if the issue is still there!

**Closed as completed by Xottab-DUTY** 2024-05-26 16:28 UTC
Labels: Bug
