### ISSUE TITLE
The Stuttering

### ISSUE THREAD

**Issue by fenderjaguarnet** [Swartz27/xray-16#1648] opened 2024-04-02 21:55 UTC
May I ask, why bother making a new engine if it doesn't actually sort out the main problem that the game has: THE STUTTERING?!

no offense, but this would be the VERY FIRST THING that should be sorted out, no?

**Comment by AMS21** [comment] 2024-04-03 06:57
First of this is not a new engine which is clearly stated in the README
> OpenXRay is an improved version of the X-Ray Engine, the game engine used in the world-famous S.T.A.L.K.E.R. game series by GSC Game World.

If you're unhappy about the direction the project is heading you are free to fork the code base and do how you please.

Should you have a concrete problem which needs addressing instead of a rudely phrased question feel free to post the details here. Otherwise the [discord](https://discord.com/invite/sjRMQwv) might be a better place to ask questions.

**Comment by Xottab-DUTY** [comment] 2024-04-03 09:45
I fully agree with @AMS21.
This is an open-source project, everyone is free to work on an area of interest.

OpenXRay is not an reimplementation, it's based on the original X-Ray code. Original game had many problems, and the stuttering isn't the biggest one.
But you definitely should notice that the game runs smoother and there are less stuttering than in vanilla engine. That's because we have worked around and eliminated big part of stuttering in #407.

Also, this is a duplicate of #62.

Thank you for this anyway! You reminded me about one thing to refactor. (#142)

**Closed as completed by Xottab-DUTY** 2024-04-03 09:45 UTC
Labels: Duplicate, Invalid
