### ISSUE TITLE
Fatal Error: SOUND: Invalid emitter state

### ISSUE THREAD

**Issue by LOyoujoLI** [Swartz27/xray-16#1631] opened 2024-03-09 13:06 UTC
**Describe the bug**
When i trying to kill somebody there is high chance to crash game.

**To Reproduce**
1. Load my save file
2. Do nothing/try to survive
3. See error

**Expected behavior**
You can continue your adventure.

**Screenshots, videos**
https://youtu.be/gkG6ZXrSX-c

**BugTrap error report**
[OpenXRay_error_report_240309-155911.zip](https://github.com/OpenXRay/xray-16/files/14546336/OpenXRay_error_report_240309-155911.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 10.0.22631.3155
 - OpenXRay build version 9157, Mar 4 2024
 - S.T.A.L.K.E.R. Call of Pripyat 1.6.02 GOG Version

**Comment by antoncxx** [comment] 2024-03-09 19:28
Duplicates #1627

**Comment by AMS21** [comment] 2024-03-09 20:02
Could you maybe share your save file which leads to this crash?

**Comment by LOyoujoLI** [comment] 2024-03-10 02:58
Oops, sorry
[savedgames.zip](https://github.com/OpenXRay/xray-16/files/14548667/savedgames.zip)

**Comment by Xottab-DUTY** [comment] 2024-03-12 20:52
Duplicate of #1627.

**Closed as completed by Xottab-DUTY** 2024-03-12 20:52 UTC
Labels: Duplicate
