### ISSUE TITLE
Add openxray in flatpak

### ISSUE THREAD

**Issue by abslike** [Swartz27/xray-16#1397] opened 2023-07-13 12:42 UTC
**Is your feature request related to a problem? Please describe.**
Yep, we can add Openxray in flathub
**Describe the solution you'd like**
Add Openxray in flathub (you can make it with this wiki: https://docs.flathub.org/docs/for-app-authors/submission/

**Comment by Xottab-DUTY** [comment] 2023-08-25 06:22
Oops, this is actually a duplicate of #1050

**Closed as completed by Xottab-DUTY** 2023-08-25 06:22 UTC
Labels: Duplicate
